### ISSUE TITLE
Auto-Create ProMa Checklist from Purchase Order

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#46]
A next requirement is to get the system to create a ProMa Checklist when triggered from Purchase Order. In the Purchase Order there is some data to be filled, after it has been submitted. The system will then create a ProMa Checklist from an existing ProMa Checklist Template and a ProMa Checklist Mapping.

**Comment by roquegv** [comment]
Create a ProMa Checklist from Purchase Order:
    - Create a script that will be called from a Purchase Order.
    - Pull the values from the ProMa Check List Template:
        - for Title, Name, Description, etc, just complete the fields with dummy data for now
        - For the Proma CheckList Content table:
            - Use a ProMa Checklist Mapping
            - For each field in the ProMa Checklist Mapping table, copy the value from the Purchase Order (or the corresponding doctype like Project Contact and Address) and paste it on the value field in the current Proma CheckList Content row.

**Comment by roquegv** [comment]
Please refer to the PR https://github.com/phamos-eu/ProMa/pull/47

**Comment by njoguchris** [comment]
@roquegv Could we have a settings page to have default contacts as opposed to doing it directly into code

**Comment by roquegv** [comment]
> @roquegv Could we have a settings page to have default contacts as opposed to doing it directly into code

Hi Chris,

What you mean be default contacts? What we have now is a contact and address that are created (or fetched) from the Sonnen Work Order. I'm not seeing the need for default values :thinking:

**Comment by wojosc** [comment]
@njoguchris @roquegv as discussed we will remove all the default values from the code and use the default field from frappe UI to set the same. If that does not work for some reason it might work to add these defaults to the "ProMa Settings" Page

**Comment by roquegv** [comment]
> @njoguchris @roquegv as discussed we will remove all the default values from the code and use the default field from frappe UI to set the same. If that does not work for some reason it might work to add these defaults to the "ProMa Settings" Page

Ok, good. I'll do it.

**Comment by roquegv** [comment]
Tasks:

- [x] Allow empty values for Proma Checklist Content table
- [x] Include Proma Checklist mapping and template fields in Project
- [x] Add default values in Proma Settings
- [x] change client, customer and supplier link fields to reference: Company, Customer and Supplier doctypes
- [ ] Include a mapping process to map Purchase Order's fields to the Proma Checklist Content table
